"""empty message

Revision ID: 3c842c2aa107
Revises: 555a4fcbf6ec
Create Date: 2022-08-29 16:09:48.734208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c842c2aa107'
down_revision = '555a4fcbf6ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
