"""empty message

Revision ID: 555a4fcbf6ec
Revises: cef31c711a51
Create Date: 2022-08-29 15:07:44.589334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555a4fcbf6ec'
down_revision = 'cef31c711a51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
