"""empty message

Revision ID: 622d0f5ec549
Revises: 83d25044b9e6
Create Date: 2022-08-28 22:19:05.860972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622d0f5ec549'
down_revision = '83d25044b9e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
