"""empty message

Revision ID: cef1fcc64c3c
Revises: 2d181745fd53
Create Date: 2022-08-28 18:58:53.489739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef1fcc64c3c'
down_revision = '2d181745fd53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_acitve', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_acitve')
    # ### end Alembic commands ###
