"""empty message

Revision ID: d8361ff35dff
Revises: 622d0f5ec549
Create Date: 2022-08-29 13:24:10.501033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8361ff35dff'
down_revision = '622d0f5ec549'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
